spring.application.name=distributed
ratelimit.capacity=5
ratelimit.refill-rate=12000
ratelimit.redis-token-bucket-script-path=scripts/token_bucket.lua
ratelimit.redis-sliding-window-script-path=scripts/sliding_window_log.lua
